module.exports.blog = [
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    },
    {
        title: "Markdown cheatsheet",
        createDate: "2023-10-05 22:53",
        image: "https://res.cloudinary.com/seekda/image/upload/w_1200,h_800,c_fill,f_auto,fl_lossy,q_auto/production/AT_UAB6-12-38-03/_66347854-3649-46D6-B415-CA3E66BDC92C.jpg",
        content:
            '#StandardfeaturesThefollowing<u>markdownfeatures</u>aredefinedbythe[CommonMark][]standard,andaregenerallysupportedbyallmarkdownparsersandeditors.##HeadingsHeadingsfrom\\`h1\\`through\\`h6\\`areconstructedwitha\\`#\\`foreachlevel:\\`\\`\\`#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading\\`\\`\\`RenderstothisHTML:\\`\\`\\`html<h1>h1Heading</h1><h2>h2Heading</h2><h3>h3Heading</h3><h4>h4Heading</h4><h5>h5Heading</h5><h6>h6Heading</h6>\\`\\`\\`Whichlookslikethisinthebrowser:#h1Heading##h2Heading###h3Heading####h4Heading#####h5Heading######h6Heading**Anoteabout"Setext"Headings**Notethatthisdocumentonlydescribes[ATXheadings](https://spec.commonmark.org/0.28/#atx-headings),asitisthepreferredsyntaxforwritingheadings.However,theCommonMarkspecificationalsodescribes[Setextheadings](https://spec.commonmark.org/0.28/#setext-headings),aheadingformatthatisdenotedbyalineofdashesorequalsignesfollowingtheheading.It\'srecommendedbytheauthorofthisguidethatyouuseonlyATXheadings,astheyareeasiertowriteandreadintexteditors,andarelesslikeleytoconflictwithothersyntaxesanddemarcationsfromlanguageextensions.##ParagraphsBodycopywrittenasnormalplain-textwillbewrappedwith\\`<p></p>\\`tagsintherenderedHTML.Sothis:',
    }
];
